### ISSUE TITLE
How to visualize training results?

### ISSUE THREAD

**Issue by FENGA1** [NanqingD/DeepLabV3-Tensorflow#18]
After we get the model, how do we test it?
![image](https://user-images.githubusercontent.com/33304518/37513458-1b514eb0-2940-11e8-8a99-7b9a7e902269.png)

**Comment by yghcats** [comment]
The same question

**Comment by duan147** [comment]
Excuse me, why do I not output the value of these loss and IOU in the training stage, and my program has not been wrong, but there has been no result, I hope to get your answer? @FENGA1

**Comment by FENGA1** [comment]
Written to the log：
nohup python train_voc12.py &
tail -f nohup.out

**Comment by duan147** [comment]
What's the meaning of this? @FENGA1
