### ISSUE TITLE
Checkpoint Error

### ISSUE THREAD

**Issue by Balabala-Hong** [NanqingD/DeepLabV3-Tensorflow#21]
Hi, Nanqing,
  First, thanks a lot for your implementation, this is a great piece of work! I wonder if the pretrained model
you provided is corresponding to your code as the training have taken so much time.Could you share the snapshot that you completed?My email address is 815402907@qq.com.I'm waiting for your reply.

**Comment by HJanefer** [comment]
Hello,thanks for your implementation, I got a lot out of your work. Could you share the snapshot that you completed, if it's convenient for you? My email is 1654965767@qq.com. I'm waiting for your reply. Thank you a lot!
