### ISSUE TITLE
TRAIN on voc2012

### ISSUE THREAD

**Issue by congjianting** [NanqingD/DeepLabV3-Tensorflow#7]
你好,

非常欣赏你的工程, 我今天基于VOC2012进行了训练, 使用学习率=0.01从头训练, 感觉收敛还是很慢,

请问这个现象正常吗?  按照教程训练, 这个指标可以达到85%以上吗?

**Comment by NanqingD** [comment]
根据论文，单片GPU可能要跑三四天，取决于GPU性能， 考虑到原作者有利用ResNet，可能收敛会快一点。我大概跑了三天左右IOU能上75+， 剩下的可能要微调learning rate了。

**Comment by congjianting** [comment]
非常感谢你的回复, 非常好的工程.

**Comment by NanqingD** [comment]
@congjianting 不客气，我最后finetune的时候把batch_norm的参数都固定了，论文里有写，但我是手动改的。

**Comment by John1231983** [comment]
Hi all, could you tell me the performance of validation when train on trainaug dataset and validation on val set? The readme just shows the performance when you use train+val set (i guess). The paper reported arround 75% when used 7 blocks with multigrid (1,2,4) for resnet 101. Thanks
